dbader/node-datadog-metrics

README.md, lib/loggers.js
Adds a way to flush metrics e.g. before quitting the application.
=> Add callbacks to logger flush

README.md, index.js, lib/aggregators.js, lib/loggers.js, package.json, test/aggregators_tests.js, test/loggers_tests.js
``` javascript
var metrics = new metrics.BufferedMetricsLogger({
// ...
defaultTags: ['one', 'two']
});
metrics.increment('my_counter', 1, ['three']);
// Reports tags: one, two, three
```
=> Support default tags

lib/metrics.js, test/metrics_tests.js
update metric type `counter` to `count` as `counter` is being deprecated.
https://help.datadoghq.com/hc/en-us/articles/206955236-Metric-types-in-Datadog
```
In the web app there are 3 metric types: GAUGE, RATE, COUNT (and COUNTER, now deprecated).
```
set histogram count to type `count` as well; more precise for the type.
=> update metric type `counter` to `count`; `counter` is deprecated

package.json
dogapi added a 30-second timeout to its HTTPS requests, which lets clients handle dropped calls more gracefully.
=> Update version of dogapi dependency to 2.8.3.

lib/reporters.js
DataDogReporter always check if onSuccess is method, NullReporter doesn't.
=> Consistent check of param onSuccess

lib/reporters.js
Extended the initialization of the dogapi to support other endpoints such as the EU API, given that the dogapi already supports this. https://brettlangdon.github.io/node-dogapi/#dogapi-initialize
Also added the parameter and env options.
=> Extending initialization to support EU realm

lib/aggregators.js, lib/loggers.js, lib/metrics.js, test/metrics_tests.js
This PR adds the optional feature to choose the aggregates and percentiles in the Histograms.
Because there are situations where we only wants to have a specific aggregate and/or percentiles, so the other data generated is extra data that we don't need
This follows the code implemented on this [closed PR](https://github.com/dbader/node-datadog-metrics/pull/8). Thanks @cgiovanacci for starting this idea.
By default, if the user doesn't set the `option` value in the `histrogram` function, it will act as it is until now.
1. Add a histogram with all the aggregates and only the `p75` percentile.
```
metrics.histogram('test.service_time', 0.248, 'myhost', { percentiles: [0.75] });
```
2. Add a histogram with the `max`, `min`, and `avg` aggregates and all the percentiles.
``` …
```
=> Add feature to choose aggregates and percentiles in Histograms

index.js, lib/loggers.js, lib/metrics.js, lib/reporters.js, test/metrics_tests.js
This adds support for DataDog’s `distribution` metric type, which is sort of like a histogram except is sends every point to DataDog and does the statistics in their system, rather than in the client here. (This also can work as a solution to #53 — distribution points with the same metric name and tags won’t get overwritten on DataDog’s end; that’s actually part of the whole point of distributions as I understand it, since this is the only real feasible approach for things like AWS Lambda.)
You can call it just like you would a histogram:
```js
const metrics = require("datadog-metrics");
metrics.distribution("my.metric.name", 5.3, ["a:few", "tags:here"]);
```
I tested this a few times with a live DataDog account, and it seems to work well. The way I’ve collapsed metrics from the same …
=> Add support for distribution metrics

lib/loggers.js
Not all JavaScript environments have an `.unref()` function on timers. This guards the one usage of `.unref()` so as not to cause exceptions in environments that do not have it.
It solves the one issue explicitly called out in #43, but I didn’t actually do any testing with browsers, and don’t know if there might be other barriers to browser-based usage yet to be solved.
=> Only call `unref()` when it exists

README.md
In #71, I added support for distribution metrics, but forgot to document them! This adds a description to the README, and attempts to provide guidance about when you might want to use them vs. other metric types.
=> Document distributions in `README`

.github/workflows/ci.yml
When submitting some other pull requests, I noticed the tests don’t run or show up as checks. This adds a quick GitHub actions workflow to run them automatically (in LTS versions of Node >= 12) and give maintainers a quick hint about whether a pull request is OK. (Obviously it’s not a complete check, but this is a lot better than flying totally blind!)
I also noticed that the `package.json` file includes the JSCS and JSHint for linting, but didn’t set the workflow up to use them:
- JSCS is no longer maintained (it merged with ESLint).
- JSHint doesn’t actually work —  its defaults are geared for ES5 and earlier, and there’s not config file for the features this codebase now uses. It logs lots of errors if you try and run it.
It might be worth setting up ESLint and/or Prettier for this …
=> Add GitHub actions workflow for tests

README.md, index.js, test/module_tests.js
This lets people use the built-in `NullReporter` for tests or disabling metrics. I took the route of exposing the entire `reporters` module simplicity and consistency, although it shouldn’t actually be necessary for anyone to ever explicitly use `reporters.DataDogReporter`.
Fixes #67.
=> Publicly export built-in reporters

README.md, lib/metrics.js, test/metrics_tests.js, test/module_tests.js
This adds a `<metric>.median` output for histograms, to go along with the existing `<metric>.max`, `<metric>.avg`, etc. The matches the DataDog StatsD agent, which outputs a similar median metric when send a histogram.
Fixes #68.
=> Add median aggregation for histograms

README.md
We recently switched to GitHub actions in stead of Travis for continuous integration, but forgot to update the status image in the README. This fixes it to be based on our actual build status for the `main` branch.
The text here changed from “build” to “Continuous Integration” because that’s [the name of the workflow](https://github.com/dbader/node-datadog-metrics/blob/13b8e1eb51b95180bc8135c7a8f98552a0bea9be/.github/workflows/ci.yml#L5). If we want to adjust it, we should adjust the name in the workflow file.
See also #75.
=> Update README build status for GitHub actions

package.json
Both dependencies of this package used to exact dependencies, which can result in a lot of redundancy if a consumer of this package has other dependencies that also use `debug` or `@datadog/datadog-api-client`. Instead, we now use "compatible with" ranges to let consumers use any version of our dependencies that should work with our code.
This also updates `debug` to the current major release. (This declares anything compatible with 4.1, not 4.0, since 4.1 has an important fix.)
This *doesn’t* address development dependencies, which I’ll see about updating in a separate PR.
=> Use ranges for dependency versions

lib/aggregators.js, lib/loggers.js, lib/metrics.js, lib/reporters.js, test/aggregators_tests.js, test/loggers_tests.js, test/module_tests.js
This is a quick pass at updating some of the syntax to match newer language features I used in recent PRs (#69, #71):
- Array `.includes(x)` instead of `.indexOf(x) !== -1`.
- `for...of` loops.
- Rest/spread (`...`) syntax, and using that to modify arrays (where it’s safe!) instead of calling `concat()`, which can be slower and more memory-intense.
- Don’t use `callbackify` where not necessary.
- Arrow functions (where they do something useful).
- Newer style for functions in object literals:
```js
const object = {
someFunction (arg1, arg2) {
// ...function body here...
}
};
// is equivalent to:
const object = {
someFunction: function someFunction (arg1, arg2) {
// ...function body here...
}
};
**This does not** cover larger syntactical/structural changes, like:
- `class` syntax.
- …
```
=> Normalize new syntax from recent PRs

README.md, lib/loggers.js, lib/reporters.js, test/loggers_tests.js
It looks like the `apiHost` option was added in #50, had some fixes committed directly to the main branch later (?), and then was broken in #62 when the underlying Datadog client implementation was changed. This fixes it, and resolves #42.
The `agent` option was also broken in #62, but the PR discussion makes that look intentional (while there are no notes about breaking `apiHost`). However, only part of the implementation awas removed and it was still documented in some spots. I also cleaned all that out here.
I think it might also be a good idea to *deprecate* this option name and change it to `site`, since that’s what this is called throughout Datadog’s official docs.
=> Fix the broken `apiHost` option

README.md
This adds some additional release notes that weren’t covered in #90 because the changes were still in progress when it was merged.
I’m going ahead and just merging this since it should be non-controversial.
=> Release note updates for "in development" section

.editorconfig, .github/workflows/ci.yml, .jscsrc, .jshintrc, examples/metrics.js, lib/metrics.js, lib/reporters.js, package.json, test/aggregators_tests.js, test/loggers_tests.js, test/metrics_tests.js, test/module_tests.js
This updates the linting tools we currently have (JSHint and JSCS) to their latest versions, updates their configurations to the latest versions, and turns them on in CI. This at least gets us to something that works so we have more checking for pull requests, but a future PR should remove JSCS, since it is no longer maintained and comes with a number of security vulnerabilities.
Solves the most immediate problems in #85, but doesn’t fully close the issue.
**This needs one more commit to actually resolve lint errors.** I haven’t included it yet so we can verify CI fails.
=> Update linters and turn them on in CI

package.json, test/aggregators_tests.js, test/metrics_tests.js, test/module_tests.js
This updates Mocha and Chai (and plugins) to their latest compatible versions and fixes #87.
Mocha v10 (the latest) drops support for Node.js v12, so we can't update to it. Instead, we can update to the latest v9.x release, which at least fixes a number of security vulnerabilities. Our usage of Mocha isn't too complex so happily none of our tests need to change for this.
On the other hand, there are some big breaking changes in Chai v4, so this involves a bunch of changes to the tests. The most significant thing is that `deep` now always and only means to do a deep equality check on the value being compared to, while a new `nested` property always means that the provided *keys* might be keys or might be paths. In v3.x, `deep` was used for both in different circumstances, which led to some …
=> Update test dependencies

README.md, package.json
This adds information about the supported versions of Node.js in the README and in the `engines` field of `package.json` (so NPM can show warnings).
=> Declare supported version of Node.js

lib/reporters.js, package.json, test/loggers_tests.js
This fixes #82 by using a WeakMap to keep a separate Datadog client for each instance of `DataDogReporter`. Previously, there was a single shared client across all reporter instances, so creating a second reporter (usually by creating a second logger) would overwrite the credentials of the first reporter.
This also adds [Nock](https://www.npmjs.com/package/nock) for intercepting HTTP requests during tests (the other good option for this in JS is [Polly](https://netflix.github.io/pollyjs/), but I find it a bit more complex to set up; both have good VCR-style replay tools, although I didn’t use that here). While I was at it, I also added success/error handler tests for `flush()`.
=> Keep separate Datadog clients for each reporter

.editorconfig, .github/workflows/ci.yml, README.md, index.js, lib/loggers.js, lib/metrics.js, package.json, test/lint_text.sh
In #59, @dbenamy fixed a number of places where the text "DataDog" (incorrect) was used instead of "Datadog" (correct). People have since added more incorrect usages (many from me!), so this adds a quick script to log an error during linting to prevent re-introducing the problem.
It outputs something like ([live example](https://github.com/dbader/node-datadog-metrics/actions/runs/3119206487/jobs/5059019139)):
```
The correct spelling of "Datadog" does not capitalize the second "D".
Please fix these lines ("DataDogReporter" is allowed):
./index.js:10://     - apiKey: DataDog API key
./index.js:11://     - appKey: DataDog APP key
./lib/loggers.js:15:// This talks to the DataDog HTTP API to log a bunch of metrics.
./lib/loggers.js:19:// flushes them to DataDog.
./lib/loggers.js:21:// Look …
```
=> Add lint script for bad case on "Datadog"

.jshintrc, README.md, lib/loggers.js, lib/logging.js, lib/reporters.js, test/loggers_tests.js
This fixes #52 by making two changes:
1. Add an `onError` option where users can provide an error handler for auto-flushes, just like they do when calling `flush()` explicitly. This is useful for getting more detail about the error, doing custom logging, or sending the error to a separate error tracking service, like Sentry.io.
2. In cases where the error was not handled (either via the `onError` option or by manually calling `flush()` with an error handler), this logs the error to the console *regardless* of the environment’s `DEBUG` setting. This particular error is a pretty big deal and should not be silenced.
I did the second change by making a special logging function for errors, since `debug` does not have a concept of levels or any way to temporarily override the environment (you …
=> Be more noisy about errors and add an `onError` option

.github/workflows/ci.yml, .gitignore, README.md, index.js, lib/aggregators.js, lib/loggers.js, lib/metrics.js, lib/reporters.js, package.json, tsconfig.json
This converts most of the function/class comments in the code to JSDoc-style comments (adding some more detailed descriptions/types along the way) and uses TypeScript to build type definition files from the comments. This allows us to publish types directly from this package instead of making TypeScript users install `@types/datadog-metrics`, which is maintained separately, by hand, and isn’t always be up-to-date.
It also converts old-style classes to the newer, ES6+ class syntax. The TypeScript compiler generates clearer and less redundant type definitions when classes are used, so this actually has a meaningful impact beyond just code style.
When building types, the TypeScript compiler can perform limited validation of the actual JavaScipt code (making sure it plausibly matches the …
=> Publish TypeScript types, user newer class syntax

README.md, lib/reporters.js
undefined error with env variable DATADOG_API_HOST:
github/node-datadog-metrics/lib/reporters.js:45
this.apiHost = apiHost.replace(/^app\./i, '');
^
TypeError: Cannot read properties of undefined (reading 'replace')
at new DataDogReporter (github/node-datadog-metrics/lib/reporters.js:45:32)
at new BufferedMetricsLogger (github/node-datadog-metrics/lib/loggers.js:45:38)
at Object.init (github/node-datadog-metrics/index.js:28:20)
at Object.<anonymous> (github/node-datadog-metrics/examples/metrics.js:4:9)
at Module._compile (node:internal/modules/cjs/loader:1119:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Module.load (node:internal/modules/cjs/loader:997:32)
at Module._load (node:internal/modules/cjs/loader:838:12)
at Function.executeUserEntryPoint [as …
=> Undefined error with env variable DATADOG_API_HOST

README.md, lib/loggers.js, lib/logging.js, lib/reporters.js, test/lint_text.sh, test/loggers_tests.js, test/module_tests.js
In some other spots, I’ve noted that it might be good to rename `apiHost` to `site` so that it matches the Datadog documentation and official libraries, which all call this concept the `site`. This does so by adding a new `site` option and *deprecating* `apiHost` (so it still works, but prints a warning message) and having it set `site` under the hood.
While I was at it, I followed the lead of #59 and #98 and renamed `DataDogReporter` to `DatadogReporter` (no capital "D" in the middle). I didn’t do a deprecation here since there hasn’t yet been a release where it’s publicly visible. But we could do a deprecation instead if we want.
~**This also builds on some of the tooling in #99,** so if we want to land this, it needs to be done a little more carefully so everything merges correctly.~ …
=> Rename `apiHost` → `site` and `DataDogReporter` → `DatadogReporter`

README.md, package.json
I don’t think there’s anything left to fit into v0.11.0, so this updates the version number and release notes. If there’s nothing missing here, I’ll tag and publish after merging.
=> Prepare v0.11.0 for release

README.md, lib/reporters.js, package.json
This is a trivial change following an api deprecation to @datadog/datadog-api-client
Every time I've been using this library i get a
```
setServerVariables is deprecated, please use Configuration.setServerVariables instead.
```
on startup.
After this change, the deprecation warning has gone away
=> chore: update api usage

README.md, lib/loggers.js, test/loggers_tests.js
Hello 👋 small but important fix here.
[`aggregates`](https://github.com/dbader/node-datadog-metrics/blob/a8beb15eb1d31bd30898522101b5627c41b35ef4/lib/metrics.js#L125) is the real option used, but documentation and typing are suggesting it should be `aggregations`
=> fix: Wrong terminology in types and doc

README.md, lib/errors.js, lib/reporters.js, test/loggers_tests.js
Issue #115 demonstrated how easy it is to get confused about API vs. application keys, so I’ve added some more documentation here about the difference as well as links to the official documentation about it (https://docs.datadoghq.com/account_management/api-app-keys/).
I’ve also added a custom `AuthorizationError` class with a more explanatory message (also with links to the docs), so people should see something more helpful in their console or logs, too. If you log the full object, you’ll see something like:
```
AuthorizationError: Your Datadog API key is not authorized to send metrics. Check to make sure the DATADOG_API_KEY environment variable or the `apiKey` option is set to a valid API key for your Datadog account, and that it is not an *application* key. For more, see: …
```
=> Add more documentation about API vs. App keys

.github/dependabot.yml, .github/workflows/ci.yml
Node.js has moved forward by several major versions since our CI configuration was last updated, and this updates our CI test matrix to cover them. I've also added Dependabot for updating CI workflows, but not JS dependencies (we only want security updates there).
=> Expand CI test matrix, add dependabot for actions

.github/workflows/ci.yml, README.md, index.js, package.json, test/types_check.ts
Even though we started generating TypeScript types from the JSDoc a while back, it turns out `BufferedMetricsLogger` was getting exported as a value and not a type, which technically works in TS, but is definitely not what you want. This changes up our syntax a bit to get the compiler to do the right thing, and adds a basic test of the types to make sure we don't regress.
Fixes #119.
Worth thinking about briefly before landing: are there other types we should be taking more care to export here?
=> Export a *type* for BufferedMetricsLogger

README.md, lib/aggregators.js
The `Map` object is built for our exact use-case here. It is faster and safer than using a plain JS object (what we currently do) or an object created with `Object.create(null)`. While this is a pretty minor improvement, it’s still worthwhile!
I meant to make this change a long time ago, and then managed to totally forget about it. 😅
=> Use `Map` for aggregator buffer

package.json
In #120, I added a test of our built types. Since we do a clean build of the types before publishing, we should also do a final check of those build results just to avoid any accidental issues for things that weren't fully checked (usually CI protects us here, but since we publish manually, a final check is useful!).
I think this is pretty straightforward and I should have just done it as part of #120, so I’m going to go ahead and merge this tomorrow if there’s no feedback.
=> Check that types are valid before publishing

README.md, lib/loggers.js, lib/reporters.js
Back in #100, I renamed the `apiHost` option to `site` (in order to match up with Datadog's own docs and terminology), but forgot to rename the corresponding environment variable. This deprecates `DATADOG_API_HOST` in favor of `DATADOG_SITE` (as should have been done before). We'll remove support for the old env var when we remove `apiHost`.
=> Rename `DATADOG_API_HOST` → `DATADOG_SITE`

CONTRIBUTING.md, README.md
⚠️ ~**Depends on #128.** This describes the script in that PR, since we might not be able to run it in CI. I can also just remove that bit in order to remove this dependency.~ *(Update: That PR has been merged.)*
I’m not sure if we’re ever going to get around to scripted release process here, so I added a contributing guide that has instructions on how to do a release (including all the various bits and bobs that should be updated along the way, since [they have been missed before](https://github.com/dbader/node-datadog-metrics/issues/79)).
Fixes #91.
=> Add contributing guide with publishing instructions for maintainers

.eslintrc.json, README.md, lib/loggers.js, lib/reporters.js, package.json, test/loggers_tests.js, test/reporters_tests.js
This deprecates `onSuccess`/`onError` callbacks throughout the library and changes async functions to return promises instead. Fixes #84.
In the reporters, this lets us switch to using actual `async` functions which simplifies code slightly.
However, the main `flush()` function does not use the `async` keyword because it needs to call `catch()` on the promise it returns before actually returning it. This is a bit of a trick, and is meant to let users write code like:
```js
metrics.flush();
```
…without needing to worry about adding their own `catch()` handler. Without this, the above code would cause an async `UnhandledPromiseRejectionWarning` exception and crash their program. I *think* this is probably useful, but it is a bit special! Some alternatives:
1. Don’t worry about making this …
=> Use promises instead of callbacks

README.md, lib/loggers.js, lib/reporters.js
Every so often folks run into trouble by mixing up API and application keys. Back in #118, I added more documentation and error messaging to help clarify potential issues, but I also noticed that the application keys don’t actually seem to be needed.
I did some testing and it turns out they definitely are not needed for submitting metrics, distributions, events, or logs (we don’t do the last two, but there is an open issue about supporting events). As far as I can tell, there’s no way for Datadog users to tell what application key something was submitted with, so they really don’t seem to have any value at all for our current use cases. Given the narrow goals of this library, we probably don’t ever want to support more complicated stuff that we would need application keys for, either. …
=> Drop support for application keys

README.md, lib/reporters.js, test/reporters_tests.js
All environment variables for this library are currently prefixed with `DATADOG_`. In order to match the configuration variables used by the Datadog agent, this supports the `DD_` prefix in addition to `DATADOG_`.
The goal here is just to make configuration easier to set up. Some Datadog tools use `DATADOG_`, while others (like the agent, which this package is most similar to) use `DD_`. Others support both! It’s not surprising if people get mixed up, or want to use one set of configuration vars for all their Datadog-related stuff, so we should make that work.
Fixes #135.
=> Support `DD_` env var prefix

README.md, lib/loggers.js, lib/reporters.js, package.json, test/reporters_tests.js
This adds retry support for submitting metrics. It’s rare, but at scale most users have probably encountered some failures to send metrics (although they might not have noticed it in their logs). Fixes #108. **This is the last major item for v0.13.0!**
There are a bunch of ways to approach retries, but they fall into two main categories:
1. Retry API requests N times if they fail.
2. Keep a queue of metrics to send and add failed metrics back onto that queue. Then automatically get retried on the next flush.
I took approach 1 here, since it was much simpler to implement in the current architecture. For long running services (e.g. a web server), approach 2 is probably slightly better, but after some brief experimentation, it felt like implementing it required a lot of coordination work …
=> Retry on Datadog API errors

README.md, package.json
I’d hoped to get this done last week (see #131), but this should be pretty much good to go now!
=> Prepare to release v0.12.0

CONTRIBUTING.md, README.md
Formatting the release history with headings makes it much more scannable (for me, at least), and also helps developers using assistive technology to scan the page. It also makes the notes for individual releases linkable.
=> Reformat release history with headings

test/module_tests.js
In #125, we switched the default aync interface to promises/async/await, but missed updating the module-level tests. This updates them.
=> Use new promise interface in module tests

README.md, index.js, lib/loggers.js, test-other/types_check.ts, test/loggers_tests.js, test/module_tests.js, test/reporters_tests.js
~**This is a bit of an ugly first pass.** The code needs some cleanup and there are some open questions, but it works and has docs and tests.~ Fixes #136.
This attaches to the process’s `beforeExit` event (supported in Node.js, Deno, and Bun) when auto-flushing is enabled in order to automatically flush when a program exits. Before, you needed to remember to call `metrics.flush()` manually at the end of your program, which is easy to forget (or not even know about in the first place!).
It also adds a `close()` method (not sure about the name) that flushes and buffered metrics and disables auto-flushing. It does *not* prevent adding new metrics to the buffer, but maybe it should? (Would they error? Get dropped silently? Call the `onError` handler?)
**To-do/open questions:**
- `stop()`
- …
=> Auto-flush on process exit

README.md, package.json
Release v0.12.1 with some maintenance updates and the new `process.beforeExit` functionality from #141.
=> Prepare v0.12.1

.github/workflows/ci.yml, CONTRIBUTING.md, README.md, lib/errors.js, lib/reporters.js, package.json, test/reporters_tests.js, tsconfig.json
**This is a first pass, and is a bit speculative.** This PR drops the official Datadog client as a runtime dependency since it is *huge* (15 MB!) and imposes a lot of runtime costs and some logging confusion (e.g. #133).
The implementation here basically swaps out `@datadog/datadog-api-client` for `cross-fetch`, which is what `@datadog/datadog-api-client` was using, so the potential issues should be pretty minimal here.
I was hoping to fix the punycode deprecation warning, but was not able to do so because the dependencies causing the issue require newer versions of Node.js than we currently do (Node.js 12.0). We can upgrade `cross-fetch` (requires Node.js 14.0) or switch directly to `node-fetch` (requires Node.js 12.20, but cuts off the tacit-but-not-guaranteed-compatibility we have with …
=> Drop the official Datadog client
